# Generated by Django 6.0.1 on 2026-01-22 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='offerproduct',
            unique_together={('offer', 'product')},
        ),
    ]
