# Generated by Django 6.0.1 on 2026-02-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/images/', verbose_name='صورة العرض'),
        ),
    ]
